---
- name: Deploy MSSQL Database
  hosts: database_server
  vars_files:
    - vars.yml
  tasks:
    - name: Create Databases
      include_role:
        name: mssql
      vars:
        mssql_root_directory: "/home/eliseu/tmp/mssql"
        mssql_database: "{{ item }}"
      loop: "{{ databases }}"
