---
- set_fact:
    bucket_name: "{{ mssql_project }}-{{ database_identifier }}"

- name: Create Bucket
  s3_bucket:
    name: "{{ bucket_name }}"
    state: present
    public_access:
      block_public_acls: true
      ignore_public_acls: true
      block_public_policy: true
      restrict_public_buckets: true
    aws_access_key: "{{ mssql_aws_access_key_id }}"
    aws_secret_key: "{{ mssql_aws_secret_access_key }}"
    aws_region: "{{ mssql_aws_region }}"

- name: Create Bucket Lifecycle Deletion Rule
  s3_lifecycle:
    name: "{{ bucket_name }}"
    status: enabled
    state: present
    expiration_days: "{{ mssql_backups_expiration_days }}"
    aws_access_key: "{{ mssql_aws_access_key_id }}"
    aws_secret_key: "{{ mssql_aws_secret_access_key }}"
    aws_region: "{{ mssql_aws_region }}"
