---
- name: Create Bucket
  s3_bucket:
    name: "{{ mssql_database.bucket_name }}"
    state: present
    public_access:
      block_public_acls: true
      ignore_public_acls: true
      block_public_policy: true
      restrict_public_buckets: true
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"

- name: Create Bucket Lifecycle Deletion Rule
  s3_lifecycle:
    name: "{{ mssql_database.bucket_name }}"
    status: enabled
    state: present
    expiration_days: "{{ mssql_database.bucket_expiration_days }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
  when: mssql_database.bucket_expiration_days is defined

- name: Remove Bucket Lifecycle Deletion Rule
  s3_lifecycle:
    name: "{{ mssql_database.bucket_name }}"
    status: disabled
    state: absent
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
  when: mssql_database.bucket_expiration_days is not defined

- name: Ensure Root Directory Exists
  file:
    path: "{{ mssql_root_directory }}"
    state: directory

- name: Ensure Database Directory Exists
  file:
    path: "{{ mssql_root_directory }}/{{ mssql_database.name }}"
    state: directory

- name: Clone and Update Git Repo
  git:
    repo: https://github.com/eliseuvideira/mssql.git
    dest: "{{ mssql_root_directory }}/{{ mssql_database.name }}"

- name: Configure Permissions For Directories
  become: true
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: "10001"
    group: "root"
  with_items:
    - "{{ mssql_root_directory }}/{{ mssql_database.name }}/backups"
    - "{{ mssql_root_directory }}/{{ mssql_database.name }}/database"

- name: Ensure .env File Exists
  copy:
    content: |
      # string(Developer | Express | Standard | Enterprise | EnterpriseCore), example: Express
      MSSQL_PID={{ mssql_database.pid }}

      # string, example: 10.0.1.101
      DB_SERVER={{ mssql_database.server }}

      # string(numeric), example: 1433
      DB_PORT={{ mssql_database.port }}

      # string, example: sa
      DB_USER={{ mssql_database.user }}

      # string, example: 0JTnyEFHHdV5j90LnaqtPmpKNvwL5taMJrezZoVjtNgD
      DB_PASSWORD={{ mssql_database.password }}

      # string, example: mssql-database
      DB_DATABASE={{ mssql_database.database }}

      # string, example: AKIAIOSFODNN7EXAMPLE
      AWS_ACCESS_KEY_ID={{ aws_access_key_id }}

      # string, example: wJalrXUtnFEMILK7MDENGEbPxRfiCYEXAMPLEKEY
      AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}

      # string(s3://<bucket_name>), example: s3://mssql-backups
      AWS_S3_BUCKET=s3://{{ mssql_database.bucket_name }}

      # string(us-east-2 | sa-east-1 | ...), example: us-east-2
      AWS_REGION={{ aws_region }}
    dest: "{{ mssql_root_directory }}/{{ mssql_database.name }}/.env"

- name: Ensure Docker Compose Running
  shell: |
    #!/bin/sh
    cd "{{ mssql_root_directory }}/{{ mssql_database.name }}"
    /usr/bin/docker-compose ps mssql --status=running --quiet 2>/dev/null || true
  register: docker_compose_ps
  changed_when: docker_compose_ps.stdout == ""

- name: Start Docker Compose
  shell: |
    #!/bin/sh
    cd "{{ mssql_root_directory }}/{{ mssql_database.name }}"
    /usr/bin/docker-compose up --detach --wait
  when: docker_compose_ps.stdout == ""

- name: Wait For Database to Up
  pause:
    seconds: 10
  when: docker_compose_ps.stdout == ""

- name: Ensure Database Exists
  shell: |
    #!/bin/sh
    /usr/bin/docker run \
      --rm \
      -i \
      mcr.microsoft.com/mssql-tools \
      /opt/mssql-tools/bin/sqlcmd \
      -S "{{ mssql_database.server }},{{ mssql_database.port }}" \
      -U "{{ mssql_database.user }}" \
      -P "{{ mssql_database.password }}" \
      -h -1 \
      -s "," \
      -W \
      -Q "set nocount on; select name from sys.databases where name = '{{ mssql_database.database }}';"
  register: ensure_database_exists
  changed_when: ensure_database_exists.stdout != mssql_database.database

- name: Create Database
  shell: |
    #!/bin/sh
    /usr/bin/docker run \
      --rm \
      -i \
      mcr.microsoft.com/mssql-tools \
      /opt/mssql-tools/bin/sqlcmd \
      -S "{{ mssql_database.server }},{{ mssql_database.port }}" \
      -U "{{ mssql_database.user }}" \
      -P "{{ mssql_database.password }}" \
      -h -1 \
      -s "," \
      -W \
      -Q "create database [{{ mssql_database.database }}];"
  when: ensure_database_exists.stdout != mssql_database.database

- name: Configure Crontab Backups
  become: true
  become_user: root
  cron:
    name: "MSSQL Database Backup for {{ mssql_database.name }}"
    minute: "20"
    hour: "*/4"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "{{ mssql_root_directory }}/{{ mssql_database.name }}/scripts/create-backup"
